"""

Revision ID: ab204a51e91b
Revises: 5094fc9e1a89
Create Date: 2021-12-13 01:04:22.140104

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'ab204a51e91b'
down_revision = '5094fc9e1a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
