"""

Revision ID: 7b61522cf459
Revises: 5d3d3021b3b8
Create Date: 2021-12-12 01:23:05.058779

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '7b61522cf459'
down_revision = '5d3d3021b3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
