"""

Revision ID: 29ab1502a0b6
Revises: c95f65aea096
Create Date: 2021-12-12 02:21:00.182578

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '29ab1502a0b6'
down_revision = 'c95f65aea096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
