"""

Revision ID: f0ee241d6351
Revises: 5ddd50379ff9
Create Date: 2021-12-12 01:31:51.182746

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'f0ee241d6351'
down_revision = '5ddd50379ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
