"""

Revision ID: c6cece9bc5b4
Revises: 1e2afae32567
Create Date: 2021-12-08 13:43:58.777997

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'c6cece9bc5b4'
down_revision = '1e2afae32567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
