"""

Revision ID: e9f9453e22b7
Revises: 29ab1502a0b6
Create Date: 2021-12-12 02:39:00.735431

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'e9f9453e22b7'
down_revision = '29ab1502a0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
