"""

Revision ID: a118d5329b82
Revises: a918915e6410
Create Date: 2021-12-13 03:03:42.295097

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a118d5329b82'
down_revision = 'a918915e6410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilization',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('utilized', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
