"""

Revision ID: 0d17b2490101
Revises: fc281c4aa7be
Create Date: 2021-12-08 10:25:39.330358

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '0d17b2490101'
down_revision = 'fc281c4aa7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_line_items', sa.Column('decision', sa.Enum('approved', 'denied', name='decisiontypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_line_items', 'decision')
    # ### end Alembic commands ###
