"""

Revision ID: 2c363b4a0af3
Revises: a055c33b3494
Create Date: 2021-12-11 21:21:45.392284

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '2c363b4a0af3'
down_revision = 'a055c33b3494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
