"""

Revision ID: 618b7dd5e87e
Revises: 
Create Date: 2021-06-11 11:23:24.541131

"""
import uuid

import arrow
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields

# revision identifiers, used by Alembic.
revision = '618b7dd5e87e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'claims',
        sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column('deleted_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column('id', src.models.fields.uuid.UUID(length=16), nullable=False),
        sa.Column('claim_type', sa.Enum('prevent', 'protect', name='claimtypeenum'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'claim_line_items',
        sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column('deleted_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column('id', src.models.fields.uuid.UUID(length=16), nullable=False),
        sa.Column('amount_claimed', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('claim_line_item_type', sa.Enum('vaccine', 'wellness_exam', 'blood_test',
                                                  name='claimlineitemtypeenum'),
                  nullable=True),
        sa.Column('claim_id', src.models.fields.uuid.UUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    op.create_table(
        'utilization',
        sa.Column('id', src.models.fields.uuid.UUID(length=16), nullable=False),
        sa.Column('utilized', sa.Integer(), nullable=False),
        sa.Column('total', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['claim_line_item_id'], ['claim_line_items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('utilization')
    op.drop_table('claim_line_items')
    op.drop_table('claims')
    # ### end Alembic commands ###
