"""

Revision ID: 9b972254b0b9
Revises: b85f2ab45d71
Create Date: 2021-12-12 02:56:22.310185

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '9b972254b0b9'
down_revision = 'b85f2ab45d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
