"""

Revision ID: 3b21a1ca16b0
Revises: 5c1b470a26e5
Create Date: 2021-12-12 01:15:39.765093

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '3b21a1ca16b0'
down_revision = '5c1b470a26e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
