"""

Revision ID: b85f2ab45d71
Revises: e5c71354ce5d
Create Date: 2021-12-12 02:47:55.293194

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'b85f2ab45d71'
down_revision = 'e5c71354ce5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
