"""

Revision ID: 8bd80c87e2f6
Revises: 835de92bfd24
Create Date: 2021-12-13 02:19:39.947281

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '8bd80c87e2f6'
down_revision = '835de92bfd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
