"""

Revision ID: 835de92bfd24
Revises: ab204a51e91b
Create Date: 2021-12-13 02:14:03.757954

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '835de92bfd24'
down_revision = 'ab204a51e91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('utilization_ibfk_1', 'utilization', type_='foreignkey')
    op.drop_column('utilization', 'claim_line_item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilization', sa.Column('claim_line_item_id', sa.BINARY(length=16), nullable=False))
    op.create_foreign_key('utilization_ibfk_1', 'utilization', 'claim_line_items', ['claim_line_item_id'], ['id'])
    # ### end Alembic commands ###
