"""

Revision ID: 5094fc9e1a89
Revises: ef071aec07a1
Create Date: 2021-12-13 00:16:34.939117

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '5094fc9e1a89'
down_revision = 'ef071aec07a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
