"""

Revision ID: 5ddd50379ff9
Revises: 7b61522cf459
Create Date: 2021-12-12 01:25:57.244928

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '5ddd50379ff9'
down_revision = '7b61522cf459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
