"""

Revision ID: 3c185fd421bc
Revises: f511983b2248
Create Date: 2021-12-12 00:54:54.118999

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '3c185fd421bc'
down_revision = 'f511983b2248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
