"""

Revision ID: ec4cfffc03a5
Revises: 2999fefc728f
Create Date: 2021-12-11 22:25:18.137701

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'ec4cfffc03a5'
down_revision = '2999fefc728f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
