"""

Revision ID: e5c71354ce5d
Revises: e9f9453e22b7
Create Date: 2021-12-12 02:42:36.701191

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = 'e5c71354ce5d'
down_revision = 'e9f9453e22b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
