"""

Revision ID: 454a04e0b0bb
Revises: 618b7dd5e87e
Create Date: 2021-06-14 12:53:15.561971

"""
import uuid

import arrow
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

import src.models.fields


# revision identifiers, used by Alembic.
revision = '454a04e0b0bb'
down_revision = '618b7dd5e87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    plans_table = op.create_table('plans',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('deleted_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', src.models.fields.uuid.UUID(length=16), nullable=False),
    sa.Column('vaccines', sa.Integer(), nullable=False),
    sa.Column('wellness_exam', sa.Integer(), nullable=False),
    sa.Column('blood_test', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('claims', sa.Column('plan_id', src.models.fields.uuid.UUID(length=16), nullable=False))
    op.create_foreign_key(None, 'claims', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'plan_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
